import styled from "styled-components";

export const Title = styled.p`
  font-size: 1.8rem;
  color: #fff;
  font-weight: bold;
  letter-spacing: 0.05rem;
  font-family: Roboto;
  background: red;
  margin: 0 0.5rem 0 0.5rem;
`;
export const Box = styled.div`
  display: ${({ display }) => display || "flex"};
  background: ${({ bg }) => bg};
  height: ${({ hg }) => hg};
  width: ${({ wd }) => wd};
  flex-direction: ${({ flexDir }) => flexDir};
  justify-content: ${({ jfCont }) => jfCont};
  align-items: ${({ alItems }) => alItems};
  transform: rotate(${({ rotate }) => rotate}deg);
  box-shadow: ${({ bxSh }) => bxSh};
  position: ${({ pos }) => pos};
  top: ${({ posTop }) => posTop};
  left: ${({ posLeft }) => posLeft};
  z-index: ${({ zInd }) => zInd};
  margin: ${({ mr }) => mr};
  margin-bottom: ${({ mb }) => mb};
  margin-top: ${({ mt }) => mt};
  margin-right: ${({ mr }) => mr};
  margin-left: ${({ ml }) => ml};
  padding: ${({ pd }) => pd};
`;
//   clip-path: polygon(0 0, 100% 16%, 100% 100%, 0 88%);
export const IconImg = styled.img`
  border-radius: 50%;
  //   width: 40rem;
  height: 50%;
  filter: drop-shadow(0 0 4rem cyan);
`;
export const ButtonContactMe = styled.button`
  width: 11rem;
  height: 2.2rem;
  font-size: 1rem;
  border-radius: 0.5rem;
  background: #343f4f;
  color: #fff;
  font-weight: 500;
  letter-spacing: 0.05rem;
  box-shadow: 2px 2px 0.6rem 0.01rem gray;
  cursor: pointer;
`;
export const Div = styled.div`
  display: ${({ display }) => display || "flex"};
  background: ${({ bg }) => bg};
  height: ${({ hg }) => hg || "max-content"};
  width: ${({ wd }) => wd};
  flex-direction: ${({ flexDir }) => flexDir};
  justify-content: ${({ jfCont }) => jfCont};
  align-items: ${({ alItems }) => alItems};
  transform: rotate(${({ rotate }) => rotate}deg);
  box-shadow: ${({ bxSh }) => bxSh};
  position: ${({ pos }) => pos};
  top: ${({ posTop }) => posTop};
  left: ${({ posLeft }) => posLeft};
  z-index: ${({ zInd }) => zInd};
  margin: ${({ mr }) => mr};
  margin-bottom: ${({ mb }) => mb};
  margin-top: ${({ mt }) => mt};
  margin-right: ${({ mr }) => mr};
  margin-left: ${({ ml }) => ml};
  padding: ${({ pd }) => pd};
  border-radius: ${({ br }) => br};
  box-shadow: ${({ bxSh }) => bxSh};
  flex-wrap: ${({ flWr }) => flWr};
`;
export const P = styled.p`
  display: ${({ display }) => display || "flex"};
  background: ${({ bg }) => bg};
  color: ${({ color }) => color};
  height: ${({ hg }) => hg};
  width: ${({ wd }) => wd};
  flex-direction: ${({ flexDir }) => flexDir};
  justify-content: ${({ jfCont }) => jfCont};
  align-items: ${({ alItems }) => alItems};
  transform: rotate(${({ rotate }) => rotate}deg);
  box-shadow: ${({ bxSh }) => bxSh};
  position: ${({ pos }) => pos};
  top: ${({ posTop }) => posTop};
  left: ${({ posLeft }) => posLeft};
  z-index: ${({ zInd }) => zInd};
  margin: ${({ mr }) => mr};
  margin-bottom: ${({ mb }) => mb};
  margin-top: ${({ mt }) => mt};
  margin-right: ${({ mr }) => mr};
  margin-left: ${({ ml }) => ml};
  padding: ${({ pd }) => pd};
  font-size: ${({ fSize }) => fSize};
  font-weight: ${({ fWeight }) => fWeight};
`;
